### ISSUE TITLE
Dúvida - Utilização

### ISSUE THREAD

**Issue by Entreprise005** [tst-labs/esocial#269]
Olá, gostaria de saber se tem algum contato mais direcionado para tirar dúvidas. Estou tendo dificuldades em usar a API e também como foi me dado recentemente a questão do implantação do esocial não sei muito bem como funciona. 
Estou no Instituto Municipal de Campo Grande - MS, aqui só tem duas pessoas do TI, que sou eu e a gerente de TI, estamos encontrando dificuldades com a implementação do esocial e encontramos esse repositório que talvez possa nos ajudar a resolver essa questão, por isso o motivo do contato. 
Deixo meu email para entrar em contato, caso for pra ajudar. 
endrewprigol@gmail.com

**Comment by tiagobentotst** [comment]
Boa tarde Endrew,

Para as dúvidas no ambiente do eSocial no Governo Federal há um canal conforme as instruções abaixo: 
```Estará disponível às terças, a partir de 14:30 às 17:00 e às quintas, de 14:30 às 17:00. sala de atendimento para dúvidas sobre eSocial. Para acessar a sala, obrigatoriamente o ente deverá:

Acessar pelo computador ou notebook;
Colocar nome e munícipio ao logar no Teams;
Possuir microfone para comunicação;
Caso o equipamento não possua microfone, o ente pode utilizar o celular para comunicação e o computador para projeção de tela.
Link: https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZWFkZDI0MDEtOGFkOS00NDJhLWE2NjUtYWE1Nzk1M2RmZWQw%40thread.v2/0?context=%7b%22Tid%22%3a%223ec92969-5a51-4f18-8ac9-ef98fbafa978%22%2c%22Oid%22%3a%222bbcf8e2-2a7b-4dae-a5c6-077331265d4b%22%7d

```

Sobre as duvidas relacionadas ao eSocial-JT você pode tirar por aqui mesmo, com apoio da equipe e da comunidade.

**Comment by Entreprise005** [comment]
Boa tarde Tiago, 

Obrigado pelo link da reunião do Teams. Sobre o eSocial-JT, fiz a instalação como aplicação Java mas na hora de executar através da linha de comando
`java -jar .\src\esocial-jt-service\target\esocial-jt-service-0.0.1-SNAPSHOT.jar`
Me informa que a tentativa de conexão falhou.
Essa falha na conexão é devido a não estar com o certificado no computador ? 
Vou postar outro comentário com a saída do terminal.

**Comment by Entreprise005** [comment]
org.postgresql.util.PSQLException: A tentativa de conexÒo falhou.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:313) ~[postgresql-42.3.1.jar!/:42.3.1]
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[postgresql-42.3.1.jar!/:42.3.1]
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225) ~[postgresql-42.3.1.jar!/:42.3.1]
        at org.postgresql.Driver.makeConnection(Driver.java:466) ~[postgresql-42.3.1.jar!/:42.3.1]
        at org.postgresql.Driver.connect(Driver.java:265) ~[postgresql-42.3.1.jar!/:42.3.1]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar!/:na]
        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:52) ~[flyway-core-8.0.4.jar!/:na]
        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74) ~[flyway-core-8.0.4.jar!/:na]
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:136) ~[flyway-core-8.0.4.jar!/:na]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:121) ~[flyway-core-8.0.4.jar!/:na]
        at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfig
ure-2.6.1.jar!/:2.6.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-be
ans-5.3.13.jar!/:5.3.13]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans
-5.3.13.jar!/:5.3.13]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.
3.13.jar!/:5.3.13]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.
13.jar!/:5.3.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.13.jar!/:5.3.13]      
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.13.jar!/:5
.3.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.13.jar!/:5.3.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.13.jar!/:5.3.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.13.jar!/:5.3.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.13.jar!/:5.3.13]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154) ~[spring-context-5.3.13.jar!/:5.3.13]      
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908) ~[spring-context-5.3
.13.jar!/:5.3.13]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.13.jar!/:5.3.13]       
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.1
.jar!/:2.6.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-2.6.1.jar!/:2.6.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) ~[spring-boot-2.6.1.jar!/:2.6.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.1.jar!/:2.6.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.1.jar!/:2.6.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) ~[spring-boot-2.6.1.jar!/:2.6.1]
        at br.jus.tst.esocialjt.EsocialApplication.main(EsocialApplication.java:16) ~[classes!/:0.0.1-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[esocial-jt-service-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[esocial-jt-service-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[esocial-jt-service-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[esocial-jt-service-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
Caused by: java.net.UnknownHostException: esocial-db
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[na:na]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
        at org.postgresql.core.PGStream.createSocket(PGStream.java:238) ~[postgresql-42.3.1.jar!/:42.3.1]
        at org.postgresql.core.PGStream.<init>(PGStream.java:98) ~[postgresql-42.3.1.jar!/:42.3.1]
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:100) ~[postgresql-42.3.1.jar!/:42.3.1]
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:215) ~[postgresql-42.3.1.jar!/:42.3.1]
        ... 44 common frames omitted

2022-03-21 13:51:19.696  WARN 640 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling
 refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/sp
ringframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core
.internal.exception.FlywaySqlException: Unable to obtain connection from database: A tentativa de conexÒo falhou.
-------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : A tentativa de conexÒo falhou.

2022-03-21 13:51:19.712  INFO 640 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-03-21 13:51:19.787  INFO 640 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-03-21 13:51:19.943 ERROR 640 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot
/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.exceptio
n.FlywaySqlException: Unable to obtain connection from database: A tentativa de conexÒo falhou.
-------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : A tentativa de conexÒo falhou.

        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans
-5.3.13.jar!/:5.3.13]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.
3.13.jar!/:5.3.13]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.
13.jar!/:5.3.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.13.jar!/:5.3.13]      
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.13.jar!/:5
.3.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.13.jar!/:5.3.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.13.jar!/:5.3.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.13.jar!/:5.3.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.13.jar!/:5.3.13]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154) ~[spring-context-5.3.13.jar!/:5.3.13]      
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908) ~[spring-context-5.3
.13.jar!/:5.3.13]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.13.jar!/:5.3.13]       
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.1
.jar!/:2.6.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-2.6.1.jar!/:2.6.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) ~[spring-boot-2.6.1.jar!/:2.6.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.1.jar!/:2.6.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.1.jar!/:2.6.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) ~[spring-boot-2.6.1.jar!/:2.6.1]
        at br.jus.tst.esocialjt.EsocialApplication.main(EsocialApplication.java:16) ~[classes!/:0.0.1-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[esocial-jt-service-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[esocial-jt-service-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[esocial-jt-service-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[esocial-jt-service-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: A tentativa de conexÒo falhou.
-------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : A tentativa de conexÒo falhou.

        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:67) ~[flyway-core-8.0.4.jar!/:na]
        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74) ~[flyway-core-8.0.4.jar!/:na]
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:100) ~[postgresql-42.3.1.jar!/:42.3.1]
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:215) ~[postgresql-42.3.1.jar!/:42.3.1]
        ... 44 common frames omitted

**Comment by tiagobentotst** [comment]
Sim, é necessário ter um certificado A1 válido

https://github.com/tst-labs/esocial#pr%C3%A9-requisitos

**Comment by Entreprise005** [comment]
Olá Boa tarde Tiago,

O meu certificado é do tipo A3, como faria a referência dele no arquivo de configuração ?

**Comment by tiagobentotst** [comment]
Este projeto não tem previsão de atender essa necessidade por enquanto. Mas pode-se usar a solução abaixo como referência:

https://github.com/tst-labs/esocial/issues/197

**Comment by Entreprise005** [comment]
Obrigado, 
Vou tentar essa solução aqui.

**Comment by Entreprise005** [comment]
Olá Bom dia, 
Iniciei a instalação através do docker-compose do guia rápido. Porém, não estou conseguindo acessar o banco para inserir informações, não sei se estou acessando certo, estou tentando acessar através do pgAdmin.

**Comment by Entreprise005** [comment]
Olá Boa tarde, 
Consegui fazer funcionar, sobre a tabela de rubricas, em um único arquivo json irão todas as rubricas ou tenho que enviar vários arquivos separados? Estou a perguntar, pois fico recebendo warnigs de que o nome dos objetos está repetido. e no arquivo exemplo só a uma rubrica. (Não estou familiarizado com o JSON).

**Comment by Entreprise005** [comment]
Olá bom dia, 
Como faço para mandar para a produção ou se é possível com essa aplicação, ou preciso modificar ?

**Comment by tiagobentotst** [comment]
Boa tarde
Tem que mandar um json separado para cada rubrica.

Para mandar para produção tem que mudar a propriedade `esocialjt.ambiente=PRODUCAO_RESTRITA` para `esocialjt.ambiente=PRODUCAO`

**Comment by rafaelgsilva91** [comment]
Bom dia @Entreprise005 , meu nome é Rafael sou de campo grande MS também caso precise de um auxílio, já avançamos bastante utilizando essa API que ajuda muito equipes pequenas como a nossa. Respondendo sua dúvida sobre a tabela de rubricas, nós temos quase 1000 também, te adianto que nem todas precisam ser enviadas, por exemplo as bases, e para o envio implementamos um conector que gera várias ocorrências, possibilitando o envio de todas as rubricas ao mesmo tempo, e manda para a fila do **esocial-jt-service**, que processa 50 registros por vez.

**Comment by Entreprise005** [comment]
Bom dia @rafaelgsilva91, um auxílio é muito bem vindo. Estou tentando avançar com o uso dessa API, sigo tendo dificuldades um pouco.E as rubricas, vou procurar saber quais realmente precisam ser enviadas.

**Comment by tiagobentotst** [comment]
Realmente o procedimento é da forma que o Rafael descreveu mesmo. Mas aqui processamos mais de 5000 eventos em poucos minutos, não é tão problemático.
