### ISSUE TITLE
Key (txt_nr_recibo_arq_base)=(1.1.0000000027895701077) is not present in table "est_evento"

### ISSUE THREAD

**Issue by fabiodsilva2** [tst-labs/esocial#410]
Está dando o erro do título quando subimos o jt service apontando para o ambiente de PRODUCAO:
org.postgresql.util.PSQLException: ERROR: insert or update on table "est_evento_totalizador" violates foreign key constraint "est_evento_totalizador_fk01"
  Detalhe: Key (txt_nr_recibo_arq_base)=(1.1.0000000027895701077) is not present in table "est_evento"

**Comment by rmrosa** [comment]
Cheguei no mesmo problema. Já encontrou a solução?

**Comment by rmrosa** [comment]
Aparentemente a causa foi ter deixado application.properties a configuração esocialjt.versao-esquemas-esocial="S-1.0". Atualizei para esocialjt.versao-esquemas-esocial="S-1.2"

**Comment by cjf-cesar-ferreira** [comment]
Aconteceu no meu órgão (CJF).
O eSocial deu erro no processamento do 1299 mas mesmo com erro no evento o retorno do lote veio com os dados de evento totalizador.
Tiver que fazer uma consulta na tabela EST_EVENTO para validar se o nrRecibo está gravado.

**Comment by ldbeserra** [comment]
Gente, esse erro começou a ocorrer aqui no nosso ambiente de produção desde julho.
Alguém sabe detalhar melhor do que se trata? Alguns lotes são enviados corretamente, outros ficam travados nesse erro.

```

2025-08-12 13:19:27.579 ERROR 1 --- [TaskScheduler-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: insert or update on table "est_evento_totalizador" violates foreign key constraint "est_evento_totalizador_fk01"
  Detail: Key (txt_nr_recibo_arq_base)=(1.1.0000000033955232183) is not present in table "est_evento".
2025-08-12 13:19:27.585 ERROR 1 --- [TaskScheduler-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
(...)
	at br.jus.tst.esocialjt.negocio.EventoTotalizadorServico.salvar(EventoTotalizadorServico.java:40)  at 
br.jus.tst.esocialjt.negocio.EventoTotalizadorServico$$FastClassBySpringCGLIB$$17bdb10c.invoke(<generated>) 
(...)
	at br.jus.tst.esocialjt.negocio.EventoTotalizadorServico$$EnhancerBySpringCGLIB$$7d5bbd90.salvar(<generated>) at 
br.jus.tst.esocialjt.negocio.AtualizacaoProcessamentoServico.salvaEventosTotalizadores(AtualizacaoProcessamentoServico.java:98)  at 
br.jus.tst.esocialjt.negocio.AtualizacaoProcessamentoServico.lambda$atualizarProcessamentoLote$2(AtualizacaoProcessamentoServico.java:76)
br.jus.tst.esocialjt.negocio.AtualizacaoProcessamentoServico.atualizarProcessamentoLote(AtualizacaoProcessamentoServico.java:64) at 
br.jus.tst.esocialjt.negocio.AtualizacaoProcessamentoServico.atualizarTodosEmProcessamento(AtualizacaoProcessamentoServico.java:41)
(...)
br.jus.tst.esocialjt.negocio.AtualizacaoProcessamentoServico$$EnhancerBySpringCGLIB$$4afcd57d.atualizarTodosEmProcessamento(<generated>) at
br.jus.tst.esocialjt.auto.tarefas.TarefaAtualizacaoProcessamento.executar(TarefaAtualizacaoProcessamento.java:31)  at 
br.jus.tst.esocialjt.auto.tarefas.TarefaAtualizacaoProcessamento$$FastClassBySpringCGLIB$$b57038d2.invoke(<generated>) 
```

Agradeço desde já

**Comment by ldbeserra** [comment]
Obrigado, amigo Cesar. Eu verifiquei e realmente não estamos atualizados, vou pegar a atualização.
